version: '3'
services:
  spark-master:
    image: giabar/gb-spark:master
    ports:
      - "8080:8080"
      - "7077:7077"
      - "6066:6066"
    networks:
      - spark-net

  spark-worker:
    image: giabar/gb-spark:worker
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
      - "SERVICE_PRECONDITION=spark-master:8080"
    networks:
      - spark-net
 
networks:
  spark-net:
